services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssg-web
    restart: always
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    volumes:
      - next-app-data:/app/.next/cache
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  next-app-data: 